// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5VPyg470PTkK_X4iRjnUPxf2JzZI4MAA',
    appId: '1:184714010111:web:1cc6fc387b452daf4bdbca',
    messagingSenderId: '184714010111',
    projectId: 'tahfeez-cb901',
    authDomain: 'tahfeez-cb901.firebaseapp.com',
    storageBucket: 'tahfeez-cb901.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQs70gMGDwLIKBV65RrdrFaB6tVLocec',
    appId: '1:184714010111:android:c36e88dff610c1cb4bdbca',
    messagingSenderId: '184714010111',
    projectId: 'tahfeez-cb901',
    storageBucket: 'tahfeez-cb901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpZcs1n7APzpm7cJpAGnvVDdFZLzgsa0',
    appId: '1:184714010111:ios:0e680dfd8d8648164bdbca',
    messagingSenderId: '184714010111',
    projectId: 'tahfeez-cb901',
    storageBucket: 'tahfeez-cb901.appspot.com',
    iosBundleId: 'com.example.tahfeezApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpZcs1n7APzpm7cJpAGnvVDdFZLzgsa0',
    appId: '1:184714010111:ios:c53c94dae1ad232c4bdbca',
    messagingSenderId: '184714010111',
    projectId: 'tahfeez-cb901',
    storageBucket: 'tahfeez-cb901.appspot.com',
    iosBundleId: 'com.example.tahfeezApp.RunnerTests',
  );
}
